package com.vsoftcorp.kls.dataaccess;

import java.util.List;

import com.vsoftcorp.kls.business.entities.AutoGenerationReportDef;
import com.vsoftcorp.kls.business.entities.BankParameter;
import com.vsoftcorp.kls.business.entities.PacsRepotsLog;
import com.vsoftcorp.time.Date;

public interface IDayBeginDao {
	public void updateDayBegin(BankParameter bankParameter, Date nextBusinessDate);

	public void resetVoucherNumbers(String eventType,List<Integer> pacsIdsList);
	
	public List<AutoGenerationReportDef> getAutoGenerationReportValues(String eventType);
	
	public void saveAutoGeneratedReportLog(List<PacsRepotsLog> pacsReportLogList);
}
